server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的id
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates: #断言（条件）
            - Path=/payment/lb/**
            - After=2021-12-15T11:49:34.143+08:00[Asia/Shanghai] #不在这个时间之后 不能访问服务
#            - Cookie=username,yjj  #带cookie才能访问
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id 属性且值为整数


eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: localhost:cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

